services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      POSTGRES_PASSWORD: acuriousmoon
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5436:5432

volumes:
  pgdata:
